//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Descriptors.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Descriptors.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		Count	Fragment	Count	Fragment	Count	Fragment	Count	Fragment	Count	Fragment		
        ///													
        ///ACETALS		4	CH3  AA	2	O    AA	1	&gt;C&lt;    AA						
        ///													
        ///ACYLALS (DIESTERS) 													
        ///													
        ///ACYLOINS		2	CH3  AA	1	CH   AA	1	OH    AA	1	C=O   AA				
        ///													
        ///ALCOHOLS		1	CH3  AA	1	OH    AA								
        ///													
        ///&quot;ALCOHOLS, ALLYLIC&quot;		1	CH2  AA	1	OH    AA	1	C=CH  AA	1	C=CH2  AA				
        ///													
        /// ALDEHYDES		1	R        AA	1	CH2   AA								
        ///													
        ///ALKANES		2	CH3     AA										        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Copy_of_Full_Functional_Group_List {
            get {
                return ResourceManager.GetString("Copy_of_Full_Functional_Group_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x0
        ///x1
        ///x2
        ///xp3
        ///xp4
        ///xp5
        ///xp6
        ///xp7
        ///xp8
        ///xp9
        ///xp10
        ///xc3
        ///xc4
        ///xpc4
        ///xch3
        ///xch4
        ///xch5
        ///xch6
        ///xch7
        ///xch8
        ///xch9
        ///xch10
        ///knotp
        ///xv0
        ///xv1
        ///xv2
        ///xvp3
        ///xvp4
        ///xvp5
        ///xvp6
        ///xvp7
        ///xvp8
        ///xvp9
        ///xvp10
        ///xvc3
        ///xvc4
        ///xvpc4
        ///xvch3
        ///xvch4
        ///xvch5
        ///xvch6
        ///xvch7
        ///xvch8
        ///xvch9
        ///xvch10
        ///knotpv
        ///k1
        ///k2
        ///k3
        ///ka1
        ///ka2
        ///ka3
        ///phia
        ///SsCH3
        ///SdCH2
        ///SssCH2
        ///StCH
        ///SdsCH
        ///SaaCH
        ///SsssCH
        ///SddC
        ///StsC
        ///SdssC
        ///SsaaC
        ///SaaaC
        ///SssssC
        ///SsNH2
        ///SdNH
        ///SssNH
        ///SaaNH
        ///StN
        ///SdsN
        ///SaaN
        ///SsssN
        ///SaaaN
        ///SsaaN
        ///SsNH3p
        ///SssNH2p
        ///SsssNHp
        ///SddNp
        ///StsNp
        ///SdNm
        ///Sdss [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Descriptors {
            get {
                return ResourceManager.GetString("Descriptors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As [+5 valence, one double bond]
        ///As [+5 valence, all single bonds]
        ///As [+5 valence, two double bonds]
        ///As [+3 valence, one double bond]
        ///As [+3 valence, all single bonds]
        ///As
        ///B
        ///-Br [aliphatic attach]
        ///-Br [aromatic attach]
        ///-Br [olefinic attach]
        ///-CH3 [aliphatic attach]
        ///-CH3 [aromatic attach]
        ///-CH2- [aliphatic attach]
        ///-CH2- [aromatic attach]
        ///-CH&lt; [aliphatic attach]
        ///-CH&lt; [aromatic attach]
        ///&gt;C&lt; [aliphatic attach]
        ///&gt;C&lt; [aromatic attach]
        ///=CH2 [aliphatic attach]
        ///-CH= [aromatic attach]
        ///=CH [aliphatic at [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fragments {
            get {
                return ResourceManager.GetString("fragments", resourceCulture);
            }
        }
    }
}
